export { Header } from "./Header/Header";
export { Footer } from "./Footer/Footer";
export { Layout } from "./Layout/Layout";
export { Hero } from "./Hero/Hero";
export { Filter } from "./Filter/Filter";
export { Pagination } from "./Pagination/Pagination";
export { MainProducts } from "./MainProducts/MainProducts";
export { PopularProducts } from "./PopularProducts/PopularProducts";
export { DiscountProducts } from "./DiscountProducts/DiscountProducts";
